name = "cloudflare-worker-tailscale-monitor"
account_id = "1e7680b62fbae3a24d260e08e45009dd"
main = "src/index.js"

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
preview_urls = false

kv_namespaces = [
    { binding = "TAILSCALE_NODE_STATUS_KV", preview_id = "<>", id = "5af2fcb6e3ad4c9fa540663aabfa1620" },
    { binding = "TAILSCALE_OAUTH_TOKEN_CACHE_KV", preview_id = "<>", id = "5af2fcb6e3ad4c9fa540663aabfa1620" }
]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[triggers]
crons = ["*/5 * * * *"]

[vars]
DOWN_THRESHOLD_MINUTES = "15"
REMINDER_INTERVAL_MINUTES = "240"
MONITOR_TAGS = "tag:critical" 
TOKEN_KV_KEY = "tailscale_oauth_token"
TOKEN_EXPIRY_BUFFER_SECONDS = "300"

